# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codvendedor', models.CharField(max_length=30)),
                ('periodo', models.CharField(max_length=10)),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
    ]
