# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-07 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='escalas',
            table='escalas',
        ),
    ]
